Day 7

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

import joblib

In [2]:
file_path = r"C:\Users\New Moon\Documents\Prosensia_AI_ML_Internship\Prosensia-AI-and-ML-Sabeeka\week2\task8\model_ready_features.csv"

df = pd.read_csv(file_path)

df.head()

,sales,profit,year,month,day,quarter,is_holiday,category_Clothing,category_Electronics,category_Food,...,category_Electronics.1,category_Food.1,city_Karachi.1,city_Lahore.1,DayOfWeek_Monday,DayOfWeek_Saturday,DayOfWeek_Sunday,DayOfWeek_Thursday,DayOfWeek_Tuesday,DayOfWeek_Wednesday
0,4954,836,2025,1,1,1,1,0,0,1,...,False,True,True,False,False,False,False,False,False,True
1,342,908,2025,1,2,1,0,0,1,0,...,True,False,True,False,False,False,False,True,False,False
2,2690,363,2025,1,3,1,0,0,0,1,...,False,True,False,False,False,False,False,False,False,False
3,1163,983,2025,1,4,1,0,0,0,1,...,False,True,True,False,False,True,False,False,False,False
4,4424,159,2025,1,5,1,0,0,1,0,...,True,False,False,True,False,False,True,False,False,False

In [3]:
print("Shape:", df.shape)
df.info()

Shape: (500, 25)
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   sales                   500 non-null    int64
 1   profit                  500 non-null    int64
 2   year                    500 non-null    int64
 3   month                   500 non-null    int64
 4   day                     500 non-null    int64
 5   quarter                 500 non-null    int64
 6   is_holiday              500 non-null    int64
 7   category_Clothing       500 non-null    int64
 8   category_Electronics    500 non-null    int64
 9   category_Food           500 non-null    int64
 10  city_Islamabad          500 non-null    int64
 11  city_Karachi            500 non-null    int64
 12  city_Lahore             500 non-null    int64
 13  Month                   500 non-null    int64
 14  Is_Weekend              500 non-null    int64
 15  category_Electronics.1  500 non-null    bool
 16  category_Food.1         500 non-null    bool
 17  city_Karachi.1          500 non-null    bool
 18  city_Lahore.1           500 non-null    bool
 19  DayOfWeek_Monday        500 non-null    bool
 20  DayOfWeek_Saturday      500 non-null    bool
 21  DayOfWeek_Sunday        500 non-null    bool
 22  DayOfWeek_Thursday      500 non-null    bool
 23  DayOfWeek_Tuesday       500 non-null    bool
 24  DayOfWeek_Wednesday     500 non-null    bool
dtypes: bool(10), int64(15)
memory usage: 63.6 KB

In [4]:
df["high_profit"] = (
    df.iloc[:,0] > df.iloc[:,0].median()
).astype(int)

df["high_profit"].value_counts()

high_profit
1    250
0    250
Name: count, dtype: int64

In [5]:
X = df.drop("high_profit", axis=1)
y = df["high_profit"]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Shape:", X_train.shape)
print("Testing Shape:", X_test.shape)

Training Shape: (400, 25)
Testing Shape: (100, 25)

In [7]:
lr_model = LogisticRegression(max_iter=1000)

lr_model.fit(X_train, y_train)

lr_predictions = lr_model.predict(X_test)

In [8]:
lr_accuracy = accuracy_score(y_test, lr_predictions)
lr_precision = precision_score(y_test, lr_predictions)
lr_recall = recall_score(y_test, lr_predictions)
lr_f1 = f1_score(y_test, lr_predictions)

print("Logistic Regression Results")
print("Accuracy :", lr_accuracy)
print("Precision:", lr_precision)
print("Recall   :", lr_recall)
print("F1 Score :", lr_f1)

Logistic Regression Results
Accuracy : 0.99
Precision: 1.0
Recall   : 0.9803921568627451
F1 Score : 0.9900990099009901

In [9]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [10]:
rf_predictions = rf_model.predict(X_test)

In [11]:
cm = confusion_matrix(y_test, rf_predictions)

print("Confusion Matrix")
print(cm)

Confusion Matrix
[[49  0]
 [ 1 50]]

In [12]:

rf_accuracy = accuracy_score(y_test, rf_predictions)

print("Accuracy:", rf_accuracy)

Accuracy: 0.99

In [13]:
rf_precision = precision_score(y_test, rf_predictions)

print("Precision:", rf_precision)

Precision: 1.0

In [14]:
rf_recall = recall_score(y_test, rf_predictions)

print("Recall:", rf_recall)

Recall: 0.9803921568627451

In [15]:
rf_f1 = f1_score(y_test, rf_predictions)

print("F1 Score:", rf_f1)

F1 Score: 0.9900990099009901

In [16]:
comparison = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],
    "Logistic Regression": [
        lr_accuracy,
        lr_precision,
        lr_recall,
        lr_f1
    ],
    "Random Forest": [
        rf_accuracy,
        rf_precision,
        rf_recall,
        rf_f1
    ]
})

comparison

      Metric  Logistic Regression  Random Forest
0   Accuracy             0.990000       0.990000
1  Precision             1.000000       1.000000
2     Recall             0.980392       0.980392
3   F1 Score             0.990099       0.990099

In [17]:
joblib.dump(
    rf_model,
    "random_forest_model.pkl"
)

print("Model Saved Successfully")

Model Saved Successfully

In [18]:
print("""
Conclusion:

Random Forest Classifier was implemented using
n_estimators=100 and random_state=42.

The model was trained only on training data and
evaluated on unseen test data.

Evaluation was performed using:
- Accuracy
- Precision
- Recall
- F1 Score
- Confusion Matrix
- Classification Report

Random Forest performance was compared with
Logistic Regression to determine the better model.
""")

Conclusion:

Random Forest Classifier was implemented using
n_estimators=100 and random_state=42.

The model was trained only on training data and
evaluated on unseen test data.

Evaluation was performed using:
- Accuracy
- Precision
- Recall
- F1 Score
- Confusion Matrix
- Classification Report

Random Forest performance was compared with
Logistic Regression to determine the better model.

                                                        Day 8

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [5, 10, 20],
    'min_samples_split': [2, 5]
}

In [21]:
print(param_grid)

{'n_estimators': [50, 100, 200], 'max_depth': [5, 10, 20], 'min_samples_split': [2, 5]}

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

In [23]:
grid_search = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

In [25]:
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [5, 10, 20], 'min_samples_split': [2, 5],
                         'n_estimators': [50, 100, 200]},
             scoring='accuracy')

In [26]:
print("Best Parameters:")
print(grid_search.best_params_)

Best Parameters:
{'max_depth': 5, 'min_samples_split': 2, 'n_estimators': 200}

In [27]:
print("Best CV Score:")
print(grid_search.best_score_)

Best CV Score:
0.9974999999999999

In [28]:
best_model = grid_search.best_estimator_

In [29]:
print(best_model)

RandomForestClassifier(max_depth=5, n_estimators=200, random_state=42)

In [30]:
y_pred_tuned = best_model.predict(X_test)

In [31]:
cm = confusion_matrix(y_test, y_pred_tuned)

print("Confusion Matrix")
print(cm)

Confusion Matrix
[[49  0]
 [ 1 50]]

In [32]:
print("Classification Report")
print(classification_report(y_test, y_pred_tuned))

Classification Report
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        49
           1       1.00      0.98      0.99        51

    accuracy                           0.99       100
   macro avg       0.99      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

In [33]:
tuned_accuracy = accuracy_score(y_test, y_pred_tuned)
print("Accuracy:", tuned_accuracy)

Accuracy: 0.99

In [34]:
tuned_precision = precision_score(y_test, y_pred_tuned)
print("Precision:", tuned_precision)

Precision: 1.0

In [35]:
tuned_recall = recall_score(y_test, y_pred_tuned)
print("Recall:", tuned_recall)

Recall: 0.9803921568627451

In [36]:
tuned_f1 = f1_score(y_test, y_pred_tuned)
print("F1 Score:", tuned_f1)

F1 Score: 0.9900990099009901

In [37]:
comparison = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score"],

    "Random Forest": [
        rf_accuracy,
        rf_precision,
        rf_recall,
        rf_f1
    ],

    "Tuned Random Forest": [
        tuned_accuracy,
        tuned_precision,
        tuned_recall,
        tuned_f1
    ]
})

comparison

      Metric  Random Forest  Tuned Random Forest
0   Accuracy       0.990000             0.990000
1  Precision       1.000000             1.000000
2     Recall       0.980392             0.980392
3   F1 Score       0.990099             0.990099

In [38]:
import joblib

joblib.dump(best_model, "random_forest_model.pkl")

print("Optimized model saved successfully!")

Optimized model saved successfully!

## Conclusion

The Random Forest model was optimized using GridSearchCV with 5-Fold Cross Validation.

A range of values for n_estimators, max_depth, and min_samples_split were tested automatically.

The best parameter combination was selected based on cross-validation performance.

The tuned model was then evaluated on the test dataset and compared with the baseline Random Forest model.

This approach helped improve model generalization and achieve a better balance between bias and variance while reducing the risk of overfitting.